bitcoin_price_monitor/urls.py
from django.urls import path

from . import views


app_name = 'bitcoin_price_monitor'
urlpatterns = [
    path('', views.index, name='index'),
    path('history', views.history, name='history'),
    path('bids', views.bids, name='bids'),
    path('asks', views.asks, name='asks'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bitcoin_price_monitor/', include('bitcoin_price_monitor.urls')),
    path('admin/', admin.site.urls),
]

bitcoin_price_monitor/models.py
import urllib.request
import urllib.parse
import json
import heapq

# Create your models here.


class History:
    url = 'https://www.bitstamp.net/api/v2/transactions/btcusd/'
    req = urllib.request.Request(url)

    r = urllib.request.urlopen(req).read()
    cont = json.loads(r.decode('utf-8'))

    price_list = []

    for item in cont:
        price_list.append(item['price'])

    highest_price = heapq.nlargest(1, price_list)
    lowest_price = heapq.nsmallest(1, price_list)


class Bids:
    url = 'https://www.bitstamp.net/api/v2/order_book/btcusd/'
    req = urllib.request.Request(url)

    r = urllib.request.urlopen(req).read()
    cont = json.loads(r.decode('utf-8'))

    bids_list = cont['bids']
    price_list = []
    amount_list = []
    value_list = []

    for index in range(8):
        sublist = bids_list[index]
        value_list.append(float(sublist[0]) * float(sublist[1]))


class Asks:
    url = 'https://www.bitstamp.net/api/v2/order_book/btcusd/'
    req = urllib.request.Request(url)

    r = urllib.request.urlopen(req).read()
    cont = json.loads(r.decode('utf-8'))

    asks_list = cont['asks']
    price_list = []
    amount_list = []
    value_list = []

    for index in range(8):
        sublist = asks_list[index]
        value_list.append(float(sublist[0]) * float(sublist[1]))

bitcoin_price_monitor/views.py
from django.shortcuts import render

from .models import History, Bids, Asks


def index(request):
    return render(request, 'bitcoin_price_monitor/index.html')


def history(request):

    recent_history = History

    return render(request, 'bitcoin_price_monitor/history.html', {'recent_history': recent_history})


def bids(request):

    recent_bids = Bids

    return render(request, 'bitcoin_price_monitor/bids.html', {'recent_bids': recent_bids})


def asks(request):

    recent_asks = Asks

    return render(request, 'bitcoin_price_monitor/asks.html', {'recent_asks': recent_asks})

bitcoin_price_monitor/templates/bitcoin_price_monitor/asks.html
<h1>Recent 8 Asks (Value)</h1>

<ul>
    {% for value in recent_asks.value_list %}
    <li>{{ value }}</li>
    {% endfor %}
</ul>

bitcoin_price_monitor/templates/bitcoin_price_monitor/bids.html
<h1>Recent 8 Bids (Value)</h1>

<ul>
    {% for value in recent_bids.value_list %}
    <li>{{ value }}</li>
    {% endfor %}
</ul>

bitcoin_price_monitor/templates/bitcoin_price_monitor/history.html
<h1>History (Highest and Lowest Price)</h1>

<ul>
    <li>Highest Price: {{ recent_history.highest_price }}</li>
    <li>Lowest Price: {{ recent_history.lowest_price }}</li>
</ul>

bitcoin_price_monitor/templates/bitcoin_price_monitor/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bitcoin_price_monitor/style.css' %}">

<h1>Bitcoin Price Monitor</h1>

<ul>
        <li><a href="{% url 'bitcoin_price_monitor:history' %}">{{ 'history link ' }}</a></li>
        <li><a href="{% url 'bitcoin_price_monitor:bids' %}">{{ 'bids link ' }}</a></li>
        <li><a href="{% url 'bitcoin_price_monitor:asks' %}">{{ 'asks link ' }}</a></li>
</ul>